# Generated by Django 4.0 on 2021-12-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=15)),
                ('log', models.CharField(max_length=1)),
                ('user', models.CharField(max_length=1)),
                ('time', models.CharField(max_length=26)),
                ('request_method', models.CharField(max_length=20)),
                ('request', models.CharField(max_length=500)),
                ('proto', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=3)),
                ('bytes', models.CharField(max_length=10)),
            ],
        ),
    ]
